---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
        enabled: true
        daemon_reload: true
  tasks:
    - name: Try to get distribs
      block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: https://packages.clickhouse.com/deb/pool/main/c/{{ item }}/{{ item }}_{{ clickhouse_version }}_all.deb
            dest: ./{{ item }}-{{ clickhouse_version }}.deb
            mode: '0644'
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: https://packages.clickhouse.com/deb/pool/main/c/clickhouse-common-static/clickhouse-common-static_{{ clickhouse_version }}_amd64.deb
            dest: ./clickhouse-common-static-{{ clickhouse_version }}.deb
            mode: '0655'
    - name: Install clickhouse packages
      become: true
      ansible.builtin.apt:
        deb: "{{ item }}"
      with_items:
        - ./clickhouse-common-static-{{ clickhouse_version }}.deb
        - ./clickhouse-client-{{ clickhouse_version }}.deb
        - ./clickhouse-server-{{ clickhouse_version }}.deb
      notify:
        - Start clickhouse service
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
    - name: Create database
      ansible.builtin.command: clickhouse-client -q 'create database logs;'
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0

- name: Install Vector
  hosts: vector
  handlers:
    - name: Start vector service
      become: true
      ansible.builtin.systemd:
        name: vector
        state: restarted
  tasks:
    - name: Get Vector distrib archive
      ansible.builtin.get_url:
        url: https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-gnu.tar.gz
        dest: ./vector.tar.gz
        mode: '0655'
    - name: Unarchive distrib
      ansible.builtin.unarchive:
        src: ./vector.tar.gz
        dest: ./
        remote_src: true
    - name: Create Vector install directory
      become: true
      ansible.builtin.file:
        path: "{{ vector_install_dir }}"
        state: directory
        mode: '0755'
    - name: Move Vector binary
      become: true
      ansible.builtin.copy:
        src: "./vector-x86_64-unknown-linux-gnu/bin/vector"
        dest: "{{ vector_install_dir }}/vector"
#      ansible.posix.synchronize:
#        src: "./vector-{{ vector_version }}-x86_64-unknown-linux-gnu/bin/"
#        dest: "{{ vector_install_dir }}/bin/"
#        checksum: true
#      delegate_to: "{{ hostvars[inventory_hostname].ansible_host }}"
        mode: '0755'
        remote_src: true
#    - name: Set executable permissions on Vector binary
#      ansible.builtin.file:
#        path: "{{ vector_install_dir }}/bin/vector"
#        mode: '0755'
    - name: Create Vector config directory
      become: true
      ansible.builtin.file:
        path: "{{ vector_config_dir }}"
        state: directory
        mode: '0755'
    - name: Copy Vector configuration
      become: true
      ansible.builtin.template:
        src: templates/vector/vector.toml.j2
        dest: "{{ vector_config_dir }}/vector.yaml"
        mode: '0644'
    - name: Create Vector service file
      become: true
      ansible.builtin.template:
        src: templates/vector/vector.service.j2
        dest: /etc/systemd/system/vector.service
        mode: '0644'
#    - name: Reload systemd manager configuration
#      ansible.builtin.systemd:
#        name: vector
#        enabled: true
    - name: Create Vector data directory
      become: true
      ansible.builtin.file:
        path: "{{ vector_data_dir }}"
        state: directory
        mode: '0755'
    - name: Enable Vector service
      become: true
      ansible.builtin.service:
        name: vector
        daemon_reload: true
        enabled: true
      notify:
        - Start vector service
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
