name: 08-ansible-02
services:
  host01:
    container_name: host01
    hostname: host01
    image: debian:stable
#    image: centos:centos8
    tty: true
    command: [/bin/bash]
    networks:
      - ansible-network
    build:
      context: .
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512Mb"
  host02:
    container_name: host02
    hostname: host02
    image: debian:stable
#    image: centos:centos8
    tty: true
    command: [/bin/bash]
    networks:
      - ansible-network
    build:
      context: .
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512Mb"

networks:
  ansible-network:

